### ISSUE TITLE
Serialization of 'SplTempFileObject' is not allowed

### ISSUE THREAD

**Issue by kevin-lot** [EasyCorp/easy-log-handler#28]
EasyLog formatter try to serialize an unserialazable object.
Indeed, objects based on Resources can't be serialized.

How can I filter this types of object ?

Trace
```
Fatal error: Uncaught Exception: Serialization of 'SplTempFileObject' is not allowed in /srv/http/vendor/symfony/yaml/Inline.php:141
Stack trace:
#0 /srv/http/vendor/symfony/yaml/Inline.php(141): serialize(Object(App\Infrastructure\Component\Notification\Message\Mail\Mail))
#1 /srv/http/vendor/symfony/yaml/Dumper.php(62): Symfony\Component\Yaml\Inline::dump(Object(App\Infrastructure\Component\Notification\Message\Mail\Mail), 1)
#2 /srv/http/vendor/symfony/yaml/Dumper.php(105): Symfony\Component\Yaml\Dumper->dump(Object(App\Infrastructure\Component\Notification\Message\Mail\Mail), 1, 0, 1)
#3 /srv/http/vendor/symfony/yaml/Yaml.php(99): Symfony\Component\Yaml\Dumper->dump(Array, 2, 0, 1)
#4 /srv/http/vendor/easycorp/easy-log-handler/src/EasyLogFormatter.php(369): Symfony\Component\Yaml\Yaml::dump(Array, 2, 2, 1)
#5 /srv/http/vendor/easycorp/easy-log-handler/src/EasyLogFormatter.php(521): EasyCorp\EasyLog\EasyLogFormatter->formatContext(Array)
#6 /srv/http/vendor/easycorp/easy-log-handler/src/EasyLogFormatter.php(84): EasyCo in /srv/http/vendor/symfony/yaml/Inline.php on line 141
```

**Comment by theofidry** [comment]
Since it's form the `Yaml` component, how about catch the exception in the formatter and return the type of the value if cannot be serialized? A check could also be added ahead e.g. `is_resource()` to avoid the most common cases

**Comment by javiereguiluz** [comment]
I'm closing this issue because this package is now abandoned. Thanks!
